- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - main.yml
  tags:
    - always
    - mongodb

- include_tasks: install-{{ ansible_os_family }}.yml
  tags:
    - mongodb

- name: Copy mongod.conf
  template:
    src: mongod.conf.j2
    dest: "{{ mongodb_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mongodb
  tags:
    - mongodb
    - mongodb_config

- name: Copy logrotate config file
  template:
    src: logrotate_mongod.j2
    dest: /etc/logrotate.d/mongod
    owner: root
    group: root
    mode: 0644
  tags:
    - mongodb
    - mongodb_config

- name: Start and enable mongo
  service:
    name: "{{ mongodb_service_name }}"
    enabled: true
    state: started
  tags:
    - mongodb
    - mongodb_service
